// import './global.css'
import {Rubik} from 'next/font/google'

import Navbar from './components/Navbar'
const rubik = Rubik({subsets: ['latin']})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Tailwind CDN */}
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

